// worldgdp-jhipster-vue/worldgdp/src/main/webapp/app/entities/country/country.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('worldgdpApp.country.home.title')" id="country-heading">Countries</span>
            <router-link :to="{name: 'CountryCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-country">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('worldgdpApp.country.home.createLabel')">
                    Create a new Country
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && countries && countries.length === 0">
            <span v-text="$t('worldgdpApp.country.home.notFound')">No countries found</span>
        </div>
        <div class="table-responsive" v-if="countries && countries.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-on:click="changeOrder('id')"><span v-text="$t('global.field.id')">ID</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'id'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('code')"><span v-text="$t('worldgdpApp.country.code')">Code</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'code'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('name')"><span v-text="$t('worldgdpApp.country.name')">Name</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'name'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('continent')"><span v-text="$t('worldgdpApp.country.continent')">Continent</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'continent'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('region')"><span v-text="$t('worldgdpApp.country.region')">Region</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'region'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('surfaceArea')"><span v-text="$t('worldgdpApp.country.surfaceArea')">Surface Area</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'surfaceArea'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('population')"><span v-text="$t('worldgdpApp.country.population')">Population</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'population'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('lifeExpectancy')"><span v-text="$t('worldgdpApp.country.lifeExpectancy')">Life Expectancy</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'lifeExpectancy'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('localName')"><span v-text="$t('worldgdpApp.country.localName')">Local Name</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'localName'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('governmentForm')"><span v-text="$t('worldgdpApp.country.governmentForm')">Government Form</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'governmentForm'"></jhi-sort-indicator></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="country in countries"
                    :key="country.id">
                    <td>
                        <router-link :to="{name: 'CountryView', params: {countryId: country.id}}">{{country.id}}</router-link>
                    </td>
                    <td>{{country.code}}</td>
                    <td>{{country.name}}</td>
                    <td v-text="$t('worldgdpApp.Continent.' + country.continent)">{{country.continent}}</td>
                    <td>{{country.region}}</td>
                    <td>{{country.surfaceArea}}</td>
                    <td>{{country.population}}</td>
                    <td>{{country.lifeExpectancy}}</td>
                    <td>{{country.localName}}</td>
                    <td>{{country.governmentForm}}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'CountryView', params: {countryId: country.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'CountryEdit', params: {countryId: country.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(country)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="worldgdpApp.country.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-country-heading" v-text="$t('worldgdpApp.country.delete.question', {'id': removeId})">Are you sure you want to delete this Country?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-country" v-text="$t('entity.action.delete')" v-on:click="removeCountry()">Delete</button>
            </div>
        </b-modal>
        <div v-show="countries && countries.length > 0">
            <div class="row justify-content-center">
                <jhi-item-count :page="page" :total="queryCount" :itemsPerPage="itemsPerPage"></jhi-item-count>
            </div>
            <div class="row justify-content-center">
                <b-pagination size="md" :total-rows="totalItems" v-model="page" :per-page="itemsPerPage" :change="loadPage(page)"></b-pagination>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./country.component.ts">
</script>

// worldgdp-jhipster-react/worldgdp/src/main/webapp/app/countries/search/country.tsx
import React, {useState, useEffect} from 'react';
// import {connect} from 'react-redux';
import {Link, RouteComponentProps} from 'react-router-dom';
import {Button, Col, Row, Table} from 'reactstrap';
import {Translate, ICrudGetAllAction, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount} from 'react-jhipster';
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome';

import {IRootState} from 'app/shared/reducers';
import {getEntities} from './country.reducer';
import {ICountry} from 'app/shared/model/country.model';
import {APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT} from 'app/config/constants';
import {ITEMS_PER_PAGE} from 'app/shared/util/pagination.constants';
import {overridePaginationStateWithQueryParams} from 'app/shared/util/entity-utils';

// export interface ICountryProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {
export interface ICountryProps extends RouteComponentProps<{ url: string }> {
}

export const Country = (props: ICountryProps) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE), props.location.search)
  );

  const getAllEntities = () => {
    // props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`${props.location.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  // const {countryList, match, loading, totalItems} = props;
  const {match} = props;
  return (
    <div>
      <div>Hello country search page</div>
      {/*<h2 id="country-heading">*/}
      {/*  <Translate contentKey="worldgdpApp.country.home.title">Countries</Translate>*/}
      {/*  <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">*/}
      {/*    <FontAwesomeIcon icon="plus"/>*/}
      {/*    &nbsp;*/}
      {/*    <Translate contentKey="worldgdpApp.country.home.createLabel">Create new Country</Translate>*/}
      {/*  </Link>*/}
      {/*</h2>*/}
      <div className="table-responsive">
        {/*{countryList && countryList.length > 0 ? (*/}
        {/*  <Table responsive>*/}
        {/*    <thead>*/}
        {/*    <tr>*/}
        {/*      <th className="hand" onClick={sort('id')}>*/}
        {/*        <Translate contentKey="global.field.id">ID</Translate> <FontAwesomeIcon icon="sort"/>*/}
        {/*      </th>*/}
        {/*      <th className="hand" onClick={sort('code')}>*/}
        {/*        <Translate contentKey="worldgdpApp.country.code">Code</Translate> <FontAwesomeIcon icon="sort"/>*/}
        {/*      </th>*/}
        {/*      <th className="hand" onClick={sort('name')}>*/}
        {/*        <Translate contentKey="worldgdpApp.country.name">Name</Translate> <FontAwesomeIcon icon="sort"/>*/}
        {/*      </th>*/}
        {/*      <th className="hand" onClick={sort('continent')}>*/}
        {/*        <Translate contentKey="worldgdpApp.country.continent">Continent</Translate> <FontAwesomeIcon icon="sort"/>*/}
        {/*      </th>*/}
        {/*      <th className="hand" onClick={sort('region')}>*/}
        {/*        <Translate contentKey="worldgdpApp.country.region">Region</Translate> <FontAwesomeIcon icon="sort"/>*/}
        {/*      </th>*/}
        {/*      <th className="hand" onClick={sort('surfaceArea')}>*/}
        {/*        <Translate contentKey="worldgdpApp.country.surfaceArea">Surface Area</Translate> <FontAwesomeIcon icon="sort"/>*/}
        {/*      </th>*/}
        {/*      <th className="hand" onClick={sort('population')}>*/}
        {/*        <Translate contentKey="worldgdpApp.country.population">Population</Translate> <FontAwesomeIcon icon="sort"/>*/}
        {/*      </th>*/}
        {/*      <th className="hand" onClick={sort('lifeExpectancy')}>*/}
        {/*        <Translate contentKey="worldgdpApp.country.lifeExpectancy">Life Expectancy</Translate> <FontAwesomeIcon icon="sort"/>*/}
        {/*      </th>*/}
        {/*      <th className="hand" onClick={sort('localName')}>*/}
        {/*        <Translate contentKey="worldgdpApp.country.localName">Local Name</Translate> <FontAwesomeIcon icon="sort"/>*/}
        {/*      </th>*/}
        {/*      <th className="hand" onClick={sort('governmentForm')}>*/}
        {/*        <Translate contentKey="worldgdpApp.country.governmentForm">Government Form</Translate> <FontAwesomeIcon icon="sort"/>*/}
        {/*      </th>*/}
        {/*      <th/>*/}
        {/*    </tr>*/}
        {/*    </thead>*/}
        {/*    <tbody>*/}
        {/*    {countryList.map((country, i) => (*/}
        {/*      <tr key={`entity-${i}`}>*/}
        {/*        <td>*/}
        {/*          <Button tag={Link} to={`${match.url}/${country.id}`} color="link" size="sm">*/}
        {/*            {country.id}*/}
        {/*          </Button>*/}
        {/*        </td>*/}
        {/*        <td>{country.code}</td>*/}
        {/*        <td>{country.name}</td>*/}
        {/*        <td>*/}
        {/*          <Translate contentKey={`worldgdpApp.Continent.${country.continent}`}/>*/}
        {/*        </td>*/}
        {/*        <td>{country.region}</td>*/}
        {/*        <td>{country.surfaceArea}</td>*/}
        {/*        <td>{country.population}</td>*/}
        {/*        <td>{country.lifeExpectancy}</td>*/}
        {/*        <td>{country.localName}</td>*/}
        {/*        <td>{country.governmentForm}</td>*/}
        {/*        <td className="text-right">*/}
        {/*          <div className="btn-group flex-btn-group-container">*/}
        {/*            <Button tag={Link} to={`${match.url}/${country.id}`} color="info" size="sm">*/}
        {/*              <FontAwesomeIcon icon="eye"/>{' '}*/}
        {/*              <span className="d-none d-md-inline">*/}
        {/*                  <Translate contentKey="entity.action.view">View</Translate>*/}
        {/*                </span>*/}
        {/*            </Button>*/}
        {/*            <Button*/}
        {/*              tag={Link}*/}
        {/*              to={`${match.url}/${country.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}*/}
        {/*              color="primary"*/}
        {/*              size="sm"*/}
        {/*            >*/}
        {/*              <FontAwesomeIcon icon="pencil-alt"/>{' '}*/}
        {/*              <span className="d-none d-md-inline">*/}
        {/*                  <Translate contentKey="entity.action.edit">Edit</Translate>*/}
        {/*                </span>*/}
        {/*            </Button>*/}
        {/*            <Button*/}
        {/*              tag={Link}*/}
        {/*              to={`${match.url}/${country.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}*/}
        {/*              color="danger"*/}
        {/*              size="sm"*/}
        {/*            >*/}
        {/*              <FontAwesomeIcon icon="trash"/>{' '}*/}
        {/*              <span className="d-none d-md-inline">*/}
        {/*                  <Translate contentKey="entity.action.delete">Delete</Translate>*/}
        {/*                </span>*/}
        {/*            </Button>*/}
        {/*          </div>*/}
        {/*        </td>*/}
        {/*      </tr>*/}
        {/*    ))}*/}
        {/*    </tbody>*/}
        {/*  </Table>*/}
        {/*) : (*/}
        {/*  !loading && (*/}
        {/*    <div className="alert alert-warning">*/}
        {/*      <Translate contentKey="worldgdpApp.country.home.notFound">No Countries found</Translate>*/}
        {/*    </div>*/}
        {/*  )*/}
        {/*)}*/}
      </div>
      {/*{props.totalItems ? (*/}
      {/*  <div className={countryList && countryList.length > 0 ? '' : 'd-none'}>*/}
      {/*    <Row className="justify-content-center">*/}
      {/*      <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled/>*/}
      {/*    </Row>*/}
      {/*    <Row className="justify-content-center">*/}
      {/*      <JhiPagination*/}
      {/*        activePage={paginationState.activePage}*/}
      {/*        onSelect={handlePagination}*/}
      {/*        maxButtons={5}*/}
      {/*        itemsPerPage={paginationState.itemsPerPage}*/}
      {/*        totalItems={props.totalItems}*/}
      {/*      />*/}
      {/*    </Row>*/}
      {/*  </div>*/}
      {/*) : (*/}
      {/*  ''*/}
      {/*)}*/}
    </div>
  );
};

// const mapStateToProps = ({country}: IRootState) => ({
//   countryList: country.entities,
//   loading: country.loading,
//   totalItems: country.totalItems,
// });

// const mapDispatchToProps = {
//   getEntities,
// };

// type StateProps = ReturnType<typeof mapStateToProps>;
// type DispatchProps = typeof mapDispatchToProps;

// export default connect(mapStateToProps, mapDispatchToProps)(Country);
export default (Country)
