// worldgdp-jhipster-vue/worldgdp/src/main/webapp/app/entities/country/country-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="worldgdpApp.country.home.createOrEditLabel" v-text="$t('worldgdpApp.country.home.createOrEditLabel')">Create or edit a Country</h2>
                <div>
                    <div class="form-group" v-if="country.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="country.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('worldgdpApp.country.code')" for="country-code">Code</label>
                        <input type="text" class="form-control" name="code" id="country-code"
                            :class="{'valid': !$v.country.code.$invalid, 'invalid': $v.country.code.$invalid }" v-model="$v.country.code.$model"  required/>
                        <div v-if="$v.country.code.$anyDirty && $v.country.code.$invalid">
                            <small class="form-text text-danger" v-if="!$v.country.code.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.country.code.maxLength" v-text="$t('entity.validation.maxlength', {max: 3})">
                                This field cannot be longer than 3 characters.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('worldgdpApp.country.name')" for="country-name">Name</label>
                        <input type="text" class="form-control" name="name" id="country-name"
                            :class="{'valid': !$v.country.name.$invalid, 'invalid': $v.country.name.$invalid }" v-model="$v.country.name.$model"  required/>
                        <div v-if="$v.country.name.$anyDirty && $v.country.name.$invalid">
                            <small class="form-text text-danger" v-if="!$v.country.name.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.country.name.maxLength" v-text="$t('entity.validation.maxlength', {max: 52})">
                                This field cannot be longer than 52 characters.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('worldgdpApp.country.continent')" for="country-continent">Continent</label>
                        <select class="form-control" name="continent" :class="{'valid': !$v.country.continent.$invalid, 'invalid': $v.country.continent.$invalid }" v-model="$v.country.continent.$model" id="country-continent"  required>
                            <option value="ASIA" v-bind:label="$t('worldgdpApp.Continent.ASIA')">ASIA</option>
                            <option value="EUROPE" v-bind:label="$t('worldgdpApp.Continent.EUROPE')">EUROPE</option>
                            <option value="NORTH_AMERICA" v-bind:label="$t('worldgdpApp.Continent.NORTH_AMERICA')">NORTH_AMERICA</option>
                            <option value="AFRICA" v-bind:label="$t('worldgdpApp.Continent.AFRICA')">AFRICA</option>
                            <option value="OCEANIA" v-bind:label="$t('worldgdpApp.Continent.OCEANIA')">OCEANIA</option>
                            <option value="ANTARCTICA" v-bind:label="$t('worldgdpApp.Continent.ANTARCTICA')">ANTARCTICA</option>
                            <option value="SOUTH_AMERICA" v-bind:label="$t('worldgdpApp.Continent.SOUTH_AMERICA')">SOUTH_AMERICA</option>
                        </select>
                        <div v-if="$v.country.continent.$anyDirty && $v.country.continent.$invalid">
                            <small class="form-text text-danger" v-if="!$v.country.continent.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('worldgdpApp.country.region')" for="country-region">Region</label>
                        <input type="text" class="form-control" name="region" id="country-region"
                            :class="{'valid': !$v.country.region.$invalid, 'invalid': $v.country.region.$invalid }" v-model="$v.country.region.$model"  required/>
                        <div v-if="$v.country.region.$anyDirty && $v.country.region.$invalid">
                            <small class="form-text text-danger" v-if="!$v.country.region.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.country.region.maxLength" v-text="$t('entity.validation.maxlength', {max: 26})">
                                This field cannot be longer than 26 characters.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('worldgdpApp.country.surfaceArea')" for="country-surfaceArea">Surface Area</label>
                        <input type="number" class="form-control" name="surfaceArea" id="country-surfaceArea"
                            :class="{'valid': !$v.country.surfaceArea.$invalid, 'invalid': $v.country.surfaceArea.$invalid }" v-model.number="$v.country.surfaceArea.$model"  required/>
                        <div v-if="$v.country.surfaceArea.$anyDirty && $v.country.surfaceArea.$invalid">
                            <small class="form-text text-danger" v-if="!$v.country.surfaceArea.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.country.surfaceArea.numeric" v-text="$t('entity.validation.number')">
                                This field should be a number.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('worldgdpApp.country.population')" for="country-population">Population</label>
                        <input type="number" class="form-control" name="population" id="country-population"
                            :class="{'valid': !$v.country.population.$invalid, 'invalid': $v.country.population.$invalid }" v-model.number="$v.country.population.$model"  required/>
                        <div v-if="$v.country.population.$anyDirty && $v.country.population.$invalid">
                            <small class="form-text text-danger" v-if="!$v.country.population.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.country.population.numeric" v-text="$t('entity.validation.number')">
                                This field should be a number.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('worldgdpApp.country.lifeExpectancy')" for="country-lifeExpectancy">Life Expectancy</label>
                        <input type="number" class="form-control" name="lifeExpectancy" id="country-lifeExpectancy"
                            :class="{'valid': !$v.country.lifeExpectancy.$invalid, 'invalid': $v.country.lifeExpectancy.$invalid }" v-model.number="$v.country.lifeExpectancy.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('worldgdpApp.country.localName')" for="country-localName">Local Name</label>
                        <input type="text" class="form-control" name="localName" id="country-localName"
                            :class="{'valid': !$v.country.localName.$invalid, 'invalid': $v.country.localName.$invalid }" v-model="$v.country.localName.$model"  required/>
                        <div v-if="$v.country.localName.$anyDirty && $v.country.localName.$invalid">
                            <small class="form-text text-danger" v-if="!$v.country.localName.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.country.localName.maxLength" v-text="$t('entity.validation.maxlength', {max: 45})">
                                This field cannot be longer than 45 characters.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('worldgdpApp.country.governmentForm')" for="country-governmentForm">Government Form</label>
                        <input type="text" class="form-control" name="governmentForm" id="country-governmentForm"
                            :class="{'valid': !$v.country.governmentForm.$invalid, 'invalid': $v.country.governmentForm.$invalid }" v-model="$v.country.governmentForm.$model"  required/>
                        <div v-if="$v.country.governmentForm.$anyDirty && $v.country.governmentForm.$invalid">
                            <small class="form-text text-danger" v-if="!$v.country.governmentForm.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.country.governmentForm.maxLength" v-text="$t('entity.validation.maxlength', {max: 45})">
                                This field cannot be longer than 45 characters.
                            </small>
                        </div>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.country.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./country-update.component.ts">
</script>

// worldgdp-jhipster-react/worldgdp/src/main/webapp/app/entities/country/country-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, reset } from './country.reducer';
import { ICountry } from 'app/shared/model/country.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface ICountryUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const CountryUpdate = (props: ICountryUpdateProps) => {
  const [isNew, setIsNew] = useState(!props.match.params || !props.match.params.id);

  const { countryEntity, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/country' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...countryEntity,
        ...values,
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="worldgdpApp.country.home.createOrEditLabel">
            <Translate contentKey="worldgdpApp.country.home.createOrEditLabel">Create or edit a Country</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : countryEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="country-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="country-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="codeLabel" for="country-code">
                  <Translate contentKey="worldgdpApp.country.code">Code</Translate>
                </Label>
                <AvField
                  id="country-code"
                  type="text"
                  name="code"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') },
                    maxLength: { value: 3, errorMessage: translate('entity.validation.maxlength', { max: 3 }) },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label id="nameLabel" for="country-name">
                  <Translate contentKey="worldgdpApp.country.name">Name</Translate>
                </Label>
                <AvField
                  id="country-name"
                  type="text"
                  name="name"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') },
                    maxLength: { value: 52, errorMessage: translate('entity.validation.maxlength', { max: 52 }) },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label id="continentLabel" for="country-continent">
                  <Translate contentKey="worldgdpApp.country.continent">Continent</Translate>
                </Label>
                <AvInput
                  id="country-continent"
                  type="select"
                  className="form-control"
                  name="continent"
                  value={(!isNew && countryEntity.continent) || 'ASIA'}
                >
                  <option value="ASIA">{translate('worldgdpApp.Continent.ASIA')}</option>
                  <option value="EUROPE">{translate('worldgdpApp.Continent.EUROPE')}</option>
                  <option value="NORTH_AMERICA">{translate('worldgdpApp.Continent.NORTH_AMERICA')}</option>
                  <option value="AFRICA">{translate('worldgdpApp.Continent.AFRICA')}</option>
                  <option value="OCEANIA">{translate('worldgdpApp.Continent.OCEANIA')}</option>
                  <option value="ANTARCTICA">{translate('worldgdpApp.Continent.ANTARCTICA')}</option>
                  <option value="SOUTH_AMERICA">{translate('worldgdpApp.Continent.SOUTH_AMERICA')}</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="regionLabel" for="country-region">
                  <Translate contentKey="worldgdpApp.country.region">Region</Translate>
                </Label>
                <AvField
                  id="country-region"
                  type="text"
                  name="region"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') },
                    maxLength: { value: 26, errorMessage: translate('entity.validation.maxlength', { max: 26 }) },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label id="surfaceAreaLabel" for="country-surfaceArea">
                  <Translate contentKey="worldgdpApp.country.surfaceArea">Surface Area</Translate>
                </Label>
                <AvField
                  id="country-surfaceArea"
                  type="string"
                  className="form-control"
                  name="surfaceArea"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') },
                    number: { value: true, errorMessage: translate('entity.validation.number') },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label id="populationLabel" for="country-population">
                  <Translate contentKey="worldgdpApp.country.population">Population</Translate>
                </Label>
                <AvField
                  id="country-population"
                  type="string"
                  className="form-control"
                  name="population"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') },
                    number: { value: true, errorMessage: translate('entity.validation.number') },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label id="lifeExpectancyLabel" for="country-lifeExpectancy">
                  <Translate contentKey="worldgdpApp.country.lifeExpectancy">Life Expectancy</Translate>
                </Label>
                <AvField id="country-lifeExpectancy" type="string" className="form-control" name="lifeExpectancy" />
              </AvGroup>
              <AvGroup>
                <Label id="localNameLabel" for="country-localName">
                  <Translate contentKey="worldgdpApp.country.localName">Local Name</Translate>
                </Label>
                <AvField
                  id="country-localName"
                  type="text"
                  name="localName"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') },
                    maxLength: { value: 45, errorMessage: translate('entity.validation.maxlength', { max: 45 }) },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label id="governmentFormLabel" for="country-governmentForm">
                  <Translate contentKey="worldgdpApp.country.governmentForm">Government Form</Translate>
                </Label>
                <AvField
                  id="country-governmentForm"
                  type="text"
                  name="governmentForm"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') },
                    maxLength: { value: 45, errorMessage: translate('entity.validation.maxlength', { max: 45 }) },
                  }}
                />
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/country" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  countryEntity: storeState.country.entity,
  loading: storeState.country.loading,
  updating: storeState.country.updating,
  updateSuccess: storeState.country.updateSuccess,
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(CountryUpdate);
