// worldgdp-jhipster-vue/worldgdp/src/main/webapp/app/entities/city/city-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="worldgdpApp.city.home.createOrEditLabel" v-text="$t('worldgdpApp.city.home.createOrEditLabel')">Create or edit a City</h2>
                <div>
                    <div class="form-group" v-if="city.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="city.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('worldgdpApp.city.name')" for="city-name">Name</label>
                        <input type="text" class="form-control" name="name" id="city-name"
                            :class="{'valid': !$v.city.name.$invalid, 'invalid': $v.city.name.$invalid }" v-model="$v.city.name.$model"  required/>
                        <div v-if="$v.city.name.$anyDirty && $v.city.name.$invalid">
                            <small class="form-text text-danger" v-if="!$v.city.name.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.city.name.maxLength" v-text="$t('entity.validation.maxlength', {max: 35})">
                                This field cannot be longer than 35 characters.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('worldgdpApp.city.district')" for="city-district">District</label>
                        <input type="text" class="form-control" name="district" id="city-district"
                            :class="{'valid': !$v.city.district.$invalid, 'invalid': $v.city.district.$invalid }" v-model="$v.city.district.$model"  required/>
                        <div v-if="$v.city.district.$anyDirty && $v.city.district.$invalid">
                            <small class="form-text text-danger" v-if="!$v.city.district.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.city.district.maxLength" v-text="$t('entity.validation.maxlength', {max: 20})">
                                This field cannot be longer than 20 characters.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('worldgdpApp.city.population')" for="city-population">Population</label>
                        <input type="number" class="form-control" name="population" id="city-population"
                            :class="{'valid': !$v.city.population.$invalid, 'invalid': $v.city.population.$invalid }" v-model.number="$v.city.population.$model"  required/>
                        <div v-if="$v.city.population.$anyDirty && $v.city.population.$invalid">
                            <small class="form-text text-danger" v-if="!$v.city.population.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.city.population.numeric" v-text="$t('entity.validation.number')">
                                This field should be a number.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('worldgdpApp.city.country')" for="city-country">Country</label>
                        <select class="form-control" id="city-country" name="country" v-model="$v.city.countryId.$model" required>
                            <option v-if="!city.countryId" v-bind:value="null" selected></option>
                            <option v-bind:value="countryOption.id" v-for="countryOption in countries" :key="countryOption.id">{{countryOption.name}}</option>
                        </select>
                    </div>
                    <div v-if="$v.city.countryId.$anyDirty && $v.city.countryId.$invalid">
                        <small class="form-text text-danger" v-if="!$v.city.countryId.required" v-text="$t('entity.validation.required')">
                            This field is required.
                        </small>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.city.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./city-update.component.ts">
</script>

// worldgdp-jhipster-react/worldgdp/src/main/webapp/app/entities/city/city-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { ICountry } from 'app/shared/model/country.model';
import { getEntities as getCountries } from 'app/entities/country/country.reducer';
import { getEntity, updateEntity, createEntity, reset } from './city.reducer';
import { ICity } from 'app/shared/model/city.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface ICityUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const CityUpdate = (props: ICityUpdateProps) => {
  const [countryId, setCountryId] = useState('0');
  const [isNew, setIsNew] = useState(!props.match.params || !props.match.params.id);

  const { cityEntity, countries, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/city' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }

    props.getCountries();
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...cityEntity,
        ...values,
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="worldgdpApp.city.home.createOrEditLabel">
            <Translate contentKey="worldgdpApp.city.home.createOrEditLabel">Create or edit a City</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : cityEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="city-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="city-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="nameLabel" for="city-name">
                  <Translate contentKey="worldgdpApp.city.name">Name</Translate>
                </Label>
                <AvField
                  id="city-name"
                  type="text"
                  name="name"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') },
                    maxLength: { value: 35, errorMessage: translate('entity.validation.maxlength', { max: 35 }) },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label id="districtLabel" for="city-district">
                  <Translate contentKey="worldgdpApp.city.district">District</Translate>
                </Label>
                <AvField
                  id="city-district"
                  type="text"
                  name="district"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') },
                    maxLength: { value: 20, errorMessage: translate('entity.validation.maxlength', { max: 20 }) },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label id="populationLabel" for="city-population">
                  <Translate contentKey="worldgdpApp.city.population">Population</Translate>
                </Label>
                <AvField
                  id="city-population"
                  type="string"
                  className="form-control"
                  name="population"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') },
                    number: { value: true, errorMessage: translate('entity.validation.number') },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label for="city-country">
                  <Translate contentKey="worldgdpApp.city.country">Country</Translate>
                </Label>
                <AvInput id="city-country" type="select" className="form-control" name="countryId" required>
                  {countries
                    ? countries.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.name}
                        </option>
                      ))
                    : null}
                </AvInput>
                <AvFeedback>
                  <Translate contentKey="entity.validation.required">This field is required.</Translate>
                </AvFeedback>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/city" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  countries: storeState.country.entities,
  cityEntity: storeState.city.entity,
  loading: storeState.city.loading,
  updating: storeState.city.updating,
  updateSuccess: storeState.city.updateSuccess,
});

const mapDispatchToProps = {
  getCountries,
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(CityUpdate);
