// worldgdp-jhipster-vue/worldgdp/src/main/webapp/app/entities/country-language/country-language-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="worldgdpApp.countryLanguage.home.createOrEditLabel" v-text="$t('worldgdpApp.countryLanguage.home.createOrEditLabel')">Create or edit a CountryLanguage</h2>
                <div>
                    <div class="form-group" v-if="countryLanguage.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="countryLanguage.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('worldgdpApp.countryLanguage.language')" for="country-language-language">Language</label>
                        <input type="text" class="form-control" name="language" id="country-language-language"
                            :class="{'valid': !$v.countryLanguage.language.$invalid, 'invalid': $v.countryLanguage.language.$invalid }" v-model="$v.countryLanguage.language.$model"  required/>
                        <div v-if="$v.countryLanguage.language.$anyDirty && $v.countryLanguage.language.$invalid">
                            <small class="form-text text-danger" v-if="!$v.countryLanguage.language.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('worldgdpApp.countryLanguage.isOfficial')" for="country-language-isOfficial">Is Official</label>
                        <select class="form-control" name="isOfficial" :class="{'valid': !$v.countryLanguage.isOfficial.$invalid, 'invalid': $v.countryLanguage.isOfficial.$invalid }" v-model="$v.countryLanguage.isOfficial.$model" id="country-language-isOfficial"  required>
                            <option value="T" v-bind:label="$t('worldgdpApp.TrueFalse.T')">T</option>
                            <option value="F" v-bind:label="$t('worldgdpApp.TrueFalse.F')">F</option>
                        </select>
                        <div v-if="$v.countryLanguage.isOfficial.$anyDirty && $v.countryLanguage.isOfficial.$invalid">
                            <small class="form-text text-danger" v-if="!$v.countryLanguage.isOfficial.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('worldgdpApp.countryLanguage.percentage')" for="country-language-percentage">Percentage</label>
                        <input type="number" class="form-control" name="percentage" id="country-language-percentage"
                            :class="{'valid': !$v.countryLanguage.percentage.$invalid, 'invalid': $v.countryLanguage.percentage.$invalid }" v-model.number="$v.countryLanguage.percentage.$model"  required/>
                        <div v-if="$v.countryLanguage.percentage.$anyDirty && $v.countryLanguage.percentage.$invalid">
                            <small class="form-text text-danger" v-if="!$v.countryLanguage.percentage.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.countryLanguage.percentage.numeric" v-text="$t('entity.validation.number')">
                                This field should be a number.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('worldgdpApp.countryLanguage.country')" for="country-language-country">Country</label>
                        <select class="form-control" id="country-language-country" name="country" v-model="$v.countryLanguage.countryId.$model" required>
                            <option v-if="!countryLanguage.countryId" v-bind:value="null" selected></option>
                            <option v-bind:value="countryOption.id" v-for="countryOption in countries" :key="countryOption.id">{{countryOption.name}}</option>
                        </select>
                    </div>
                    <div v-if="$v.countryLanguage.countryId.$anyDirty && $v.countryLanguage.countryId.$invalid">
                        <small class="form-text text-danger" v-if="!$v.countryLanguage.countryId.required" v-text="$t('entity.validation.required')">
                            This field is required.
                        </small>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.countryLanguage.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./country-language-update.component.ts">
</script>

// spring-5-projects/worldgdp-jhipster-react/worldgdp/src/main/webapp/app/entities/country-language/country-language-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { ICountry } from 'app/shared/model/country.model';
import { getEntities as getCountries } from 'app/entities/country/country.reducer';
import { getEntity, updateEntity, createEntity, reset } from './country-language.reducer';
import { ICountryLanguage } from 'app/shared/model/country-language.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface ICountryLanguageUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const CountryLanguageUpdate = (props: ICountryLanguageUpdateProps) => {
  const [countryId, setCountryId] = useState('0');
  const [isNew, setIsNew] = useState(!props.match.params || !props.match.params.id);

  const { countryLanguageEntity, countries, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/country-language' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }

    props.getCountries();
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...countryLanguageEntity,
        ...values,
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="worldgdpApp.countryLanguage.home.createOrEditLabel">
            <Translate contentKey="worldgdpApp.countryLanguage.home.createOrEditLabel">Create or edit a CountryLanguage</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : countryLanguageEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="country-language-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="country-language-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="languageLabel" for="country-language-language">
                  <Translate contentKey="worldgdpApp.countryLanguage.language">Language</Translate>
                </Label>
                <AvField
                  id="country-language-language"
                  type="text"
                  name="language"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label id="isOfficialLabel" for="country-language-isOfficial">
                  <Translate contentKey="worldgdpApp.countryLanguage.isOfficial">Is Official</Translate>
                </Label>
                <AvInput
                  id="country-language-isOfficial"
                  type="select"
                  className="form-control"
                  name="isOfficial"
                  value={(!isNew && countryLanguageEntity.isOfficial) || 'T'}
                >
                  <option value="T">{translate('worldgdpApp.TrueFalse.T')}</option>
                  <option value="F">{translate('worldgdpApp.TrueFalse.F')}</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="percentageLabel" for="country-language-percentage">
                  <Translate contentKey="worldgdpApp.countryLanguage.percentage">Percentage</Translate>
                </Label>
                <AvField
                  id="country-language-percentage"
                  type="string"
                  className="form-control"
                  name="percentage"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') },
                    number: { value: true, errorMessage: translate('entity.validation.number') },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label for="country-language-country">
                  <Translate contentKey="worldgdpApp.countryLanguage.country">Country</Translate>
                </Label>
                <AvInput id="country-language-country" type="select" className="form-control" name="countryId" required>
                  {countries
                    ? countries.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.name}
                        </option>
                      ))
                    : null}
                </AvInput>
                <AvFeedback>
                  <Translate contentKey="entity.validation.required">This field is required.</Translate>
                </AvFeedback>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/country-language" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  countries: storeState.country.entities,
  countryLanguageEntity: storeState.countryLanguage.entity,
  loading: storeState.countryLanguage.loading,
  updating: storeState.countryLanguage.updating,
  updateSuccess: storeState.countryLanguage.updateSuccess,
});

const mapDispatchToProps = {
  getCountries,
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(CountryLanguageUpdate);
