// spring-5-projects/worldgdp-jhipster-react/worldgdp/src/main/webapp/app/entities/country-language/country-language.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, ICrudGetAllAction, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './country-language.reducer';
import { ICountryLanguage } from 'app/shared/model/country-language.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';

export interface ICountryLanguageProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const CountryLanguage = (props: ICountryLanguageProps) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE), props.location.search)
  );

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`${props.location.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const { countryLanguageList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="country-language-heading">
        <Translate contentKey="worldgdpApp.countryLanguage.home.title">Country Languages</Translate>
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp;
          <Translate contentKey="worldgdpApp.countryLanguage.home.createLabel">Create new Country Language</Translate>
        </Link>
      </h2>
      <div className="table-responsive">
        {countryLanguageList && countryLanguageList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="global.field.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('language')}>
                  <Translate contentKey="worldgdpApp.countryLanguage.language">Language</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('isOfficial')}>
                  <Translate contentKey="worldgdpApp.countryLanguage.isOfficial">Is Official</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('percentage')}>
                  <Translate contentKey="worldgdpApp.countryLanguage.percentage">Percentage</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="worldgdpApp.countryLanguage.country">Country</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {countryLanguageList.map((countryLanguage, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${countryLanguage.id}`} color="link" size="sm">
                      {countryLanguage.id}
                    </Button>
                  </td>
                  <td>{countryLanguage.language}</td>
                  <td>
                    <Translate contentKey={`worldgdpApp.TrueFalse.${countryLanguage.isOfficial}`} />
                  </td>
                  <td>{countryLanguage.percentage}</td>
                  <td>
                    {countryLanguage.countryName ? (
                      <Link to={`country/${countryLanguage.countryId}`}>{countryLanguage.countryName}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${countryLanguage.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${countryLanguage.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${countryLanguage.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="worldgdpApp.countryLanguage.home.notFound">No Country Languages found</Translate>
            </div>
          )
        )}
      </div>
      {props.totalItems ? (
        <div className={countryLanguageList && countryLanguageList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={props.totalItems}
            />
          </Row>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = ({ countryLanguage }: IRootState) => ({
  countryLanguageList: countryLanguage.entities,
  loading: countryLanguage.loading,
  totalItems: countryLanguage.totalItems,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(CountryLanguage);

// worldgdp-jhipster-vue/worldgdp/src/main/webapp/app/entities/country-language/country-language.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('worldgdpApp.countryLanguage.home.title')" id="country-language-heading">Country Languages</span>
            <router-link :to="{name: 'CountryLanguageCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-country-language">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('worldgdpApp.countryLanguage.home.createLabel')">
                    Create a new Country Language
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && countryLanguages && countryLanguages.length === 0">
            <span v-text="$t('worldgdpApp.countryLanguage.home.notFound')">No countryLanguages found</span>
        </div>
        <div class="table-responsive" v-if="countryLanguages && countryLanguages.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-on:click="changeOrder('id')"><span v-text="$t('global.field.id')">ID</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'id'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('language')"><span v-text="$t('worldgdpApp.countryLanguage.language')">Language</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'language'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('isOfficial')"><span v-text="$t('worldgdpApp.countryLanguage.isOfficial')">Is Official</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'isOfficial'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('percentage')"><span v-text="$t('worldgdpApp.countryLanguage.percentage')">Percentage</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'percentage'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('countryName')"><span v-text="$t('worldgdpApp.countryLanguage.country')">Country</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'countryName'"></jhi-sort-indicator></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="countryLanguage in countryLanguages"
                    :key="countryLanguage.id">
                    <td>
                        <router-link :to="{name: 'CountryLanguageView', params: {countryLanguageId: countryLanguage.id}}">{{countryLanguage.id}}</router-link>
                    </td>
                    <td>{{countryLanguage.language}}</td>
                    <td v-text="$t('worldgdpApp.TrueFalse.' + countryLanguage.isOfficial)">{{countryLanguage.isOfficial}}</td>
                    <td>{{countryLanguage.percentage}}</td>
                    <td>
                        <div v-if="countryLanguage.countryId">
                            <router-link :to="{name: 'CountryView', params: {countryId: countryLanguage.countryId}}">{{countryLanguage.countryName}}</router-link>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'CountryLanguageView', params: {countryLanguageId: countryLanguage.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'CountryLanguageEdit', params: {countryLanguageId: countryLanguage.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(countryLanguage)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="worldgdpApp.countryLanguage.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-countryLanguage-heading" v-text="$t('worldgdpApp.countryLanguage.delete.question', {'id': removeId})">Are you sure you want to delete this Country Language?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-countryLanguage" v-text="$t('entity.action.delete')" v-on:click="removeCountryLanguage()">Delete</button>
            </div>
        </b-modal>
        <div v-show="countryLanguages && countryLanguages.length > 0">
            <div class="row justify-content-center">
                <jhi-item-count :page="page" :total="queryCount" :itemsPerPage="itemsPerPage"></jhi-item-count>
            </div>
            <div class="row justify-content-center">
                <b-pagination size="md" :total-rows="totalItems" v-model="page" :per-page="itemsPerPage" :change="loadPage(page)"></b-pagination>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./country-language.component.ts">
</script>
